services:
  php-apache:
    image: kubrakizilkilic/my-php-apache-app:latest
    ports:
      - "8080:80"
    volumes:
      - /var/www/html
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
