version: "3.8"
services:
  php-apache:
    build: .
    ports:
      - "8080:80"
  db:
    image: kubrakizilkilic/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend