name: Docker
on:
  push:
    branches: 
      - main

env:
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: kubra-kzlk/cloudsysProject

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username:  kubrakizilkilic
          password: ${{ secrets.dockertoken }}

      - name: Build and push Docker image
        run: 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-php-apache-app:latest .
          docker push: ${{secrets.DOCKER_USERNAME }}/my-php-apache-app:latest

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
