name: Docker
on:
  schedule:
    - cron: "31 13 * * *"
  push:
    branches: ["master"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["master"]

env:
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: kubra-kzlk/cloudsysProject

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cosign
        run: |
          COSIGN_VERSION=2.2.4
          curl -LO https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username:  kubrakizilkilic
          password: ${{ secrets.dockertoken }}

      - name: Build and push Docker image
        run: 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-php-apache-app:latest .
          docker push ${{secrets.DOCKER_USERNAME }}/my-php-apache-app:latest

      - name: Verify Cosign Installation
        run: cosign version
