version: "3.8"
services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - /var/www/html
  db:
    image: kubrakizilkilic/my-php-apache-app:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
